server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /hl7-ris/ {
    try_files $uri $uri/ /hl7-ris/index.html;
  }

  location /hl7-ris {
    try_files $uri $uri/ /hl7-ris/index.html;
  }

  location /hl7-ris/assets/ {
    try_files $uri $uri/ =404;
  }

  gzip on;
  gzip_types text/plain text/css application/javascript application/json image/svg+xml;
  gzip_min_length 1024;
  gzip_comp_level 6;

  error_page 404 /hl7-ris/index.html;
}
